# Generated by Django 3.2.15 on 2023-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_remove_book_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thesis_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
