# Generated by Django 3.2.15 on 2023-06-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_book_thesis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.teacher'),
        ),
    ]
